### ISSUE TITLE
Information in the @return

### ISSUE THREAD

**Issue by escudero89** [FGRibreau/doxx#56]
Hi,

first, thanks for developing doxx :).

I've a quesiton regarding the @return parameter in the comment block. If you have something like this:

```javascript
/**
 * Test if a symbol should be ignored or not
 * @param  {Object} symbol symbol to check against
 * @return {Boolean} true if the symbol is not private nor must be ignored
 */
function shouldPass(symbol){
    .....
 }
```

could it be that the comment in the @return parameter is ignored in the final result (see [`parser.js.html`](http://fgribreau.github.io/doxx/docs/parser.js.html))? I think that it would be useful to have it there somewhere in the final HTML.

What are your thoughts about it?

Greetings.

**Comment by forstermatth** [comment]
The return is actually parsed as a single word (the first word in your @return line) underneath the function title: 
![capture](https://cloud.githubusercontent.com/assets/3375444/5965767/ddf0db20-a7bb-11e4-9c88-41dd0631d5a6.PNG)

I was brought to this issue because currently my module from npm skips the first and last character of the first word in the return statement:

![capture](https://cloud.githubusercontent.com/assets/3375444/5965809/1ae54b6a-a7bc-11e4-9919-aa21bac93ca0.PNG)

**Comment by escudero89** [comment]
So, is not in your current milestone to add the rest of the return comment? Or are you planning to do something about it?

**Comment by FGRibreau** [comment]
@escudero89 you can definitely send a pull-request to doxx (or to dox, the comment parser) to support this feature, I'll happily merge it :)
